services:
  backend:
    build:
      context: ./eco-spectra-back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./eco-spectra-front
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
